// +build !ignore_autogenerated_openshift

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	"unsafe"

	"k8s.io/apimachinery/pkg/conversion"
	"k8s.io/apimachinery/pkg/runtime"

	config2 "github.com/openshift/template-service-broker/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*TemplateServiceBrokerConfig)(nil), (*config2.TemplateServiceBrokerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TemplateServiceBrokerConfig_To_config_TemplateServiceBrokerConfig(a.(*TemplateServiceBrokerConfig), b.(*config2.TemplateServiceBrokerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config2.TemplateServiceBrokerConfig)(nil), (*TemplateServiceBrokerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_TemplateServiceBrokerConfig_To_v1_TemplateServiceBrokerConfig(a.(*config2.TemplateServiceBrokerConfig), b.(*TemplateServiceBrokerConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_TemplateServiceBrokerConfig_To_config_TemplateServiceBrokerConfig(in *TemplateServiceBrokerConfig, out *config2.TemplateServiceBrokerConfig, s conversion.Scope) error {
	out.TemplateNamespaces = *(*[]string)(unsafe.Pointer(&TemplateNamespaces))
	return nil
}

// Convert_v1_TemplateServiceBrokerConfig_To_config_TemplateServiceBrokerConfig is an autogenerated conversion function.
func Convert_v1_TemplateServiceBrokerConfig_To_config_TemplateServiceBrokerConfig(in *TemplateServiceBrokerConfig, out *config2.TemplateServiceBrokerConfig, s conversion.Scope) error {
	return autoConvert_v1_TemplateServiceBrokerConfig_To_config_TemplateServiceBrokerConfig(in, out, s)
}

func autoConvert_config_TemplateServiceBrokerConfig_To_v1_TemplateServiceBrokerConfig(in *config2.TemplateServiceBrokerConfig, out *TemplateServiceBrokerConfig, s conversion.Scope) error {
	TemplateNamespaces = *(*[]string)(unsafe.Pointer(&in.TemplateNamespaces))
	return nil
}

// Convert_config_TemplateServiceBrokerConfig_To_v1_TemplateServiceBrokerConfig is an autogenerated conversion function.
func Convert_config_TemplateServiceBrokerConfig_To_v1_TemplateServiceBrokerConfig(in *config2.TemplateServiceBrokerConfig, out *TemplateServiceBrokerConfig, s conversion.Scope) error {
	return autoConvert_config_TemplateServiceBrokerConfig_To_v1_TemplateServiceBrokerConfig(in, out, s)
}
